export enum COMPARISON_ACTION_TYPES {
  // Compare Proposals
  COMPARE_PROPOSALS_REQUEST = 'COMPARE_PROPOSALS_REQUEST',
  COMPARE_PROPOSALS_SUCCESS = 'COMPARE_PROPOSALS_SUCCESS',
  COMPARE_PROPOSALS_FAILURE = 'COMPARE_PROPOSALS_FAILURE',

  // Get Comparison Results
  GET_COMPARISON_RESULTS_REQUEST = 'GET_COMPARISON_RESULTS_REQUEST',
  GET_COMPARISON_RESULTS_SUCCESS = 'GET_COMPARISON_RESULTS_SUCCESS',
  GET_COMPARISON_RESULTS_FAILURE = 'GET_COMPARISON_RESULTS_FAILURE',

  // Select Vendor (Add these missing action types)
  SELECT_VENDOR_REQUEST = 'SELECT_VENDOR_REQUEST',
  SELECT_VENDOR_SUCCESS = 'SELECT_VENDOR_SUCCESS',
  SELECT_VENDOR_FAILURE = 'SELECT_VENDOR_FAILURE',

  // Clear Errors
  CLEAR_COMPARISON_ERRORS = 'CLEAR_COMPARISON_ERRORS',
}