export enum EMAIL_ACTION_TYPES {
  // Send RFP to Vendors
  SEND_RFP_TO_VENDORS_REQUEST = 'SEND_RFP_TO_VENDORS_REQUEST',
  SEND_RFP_TO_VENDORS_SUCCESS = 'SEND_RFP_TO_VENDORS_SUCCESS',
  SEND_RFP_TO_VENDORS_FAILURE = 'SEND_RFP_TO_VENDORS_FAILURE',

  // Get All Emails (Inbox)
  GET_ALL_EMAILS_REQUEST = 'GET_ALL_EMAILS_REQUEST',
  GET_ALL_EMAILS_SUCCESS = 'GET_ALL_EMAILS_SUCCESS',
  GET_ALL_EMAILS_FAILURE = 'GET_ALL_EMAILS_FAILURE',

  // Get Emails by RFP
  GET_EMAILS_BY_RFP_REQUEST = 'GET_EMAILS_BY_RFP_REQUEST',
  GET_EMAILS_BY_RFP_SUCCESS = 'GET_EMAILS_BY_RFP_SUCCESS',
  GET_EMAILS_BY_RFP_FAILURE = 'GET_EMAILS_BY_RFP_FAILURE',

  // Get Email by ID
  GET_EMAIL_BY_ID_REQUEST = 'GET_EMAIL_BY_ID_REQUEST',
  GET_EMAIL_BY_ID_SUCCESS = 'GET_EMAIL_BY_ID_SUCCESS',
  GET_EMAIL_BY_ID_FAILURE = 'GET_EMAIL_BY_ID_FAILURE',

  // Clear Errors
  CLEAR_EMAIL_ERRORS = 'CLEAR_EMAIL_ERRORS',
}